### ISSUE TITLE
get_interface is null

### ISSUE THREAD

**Issue by lal12** [daurnimator/ldbus#11]
I wrote a service which replies to dbus method calls. The problem is that I cannot get the interface, calling `msg:get_interface()` results in nil every time, but if I monitor the bus with `busctl monitor` or with `dbus-monitor` it shows the interface. Also the match filter does not seem to work on interface, but it does work on destination.

**Comment by daurnimator** [comment]
Do you have a piece of sample code showing how you are receiving messages?

**Comment by daurnimator** [comment]
Closing due to lack of reply
