### ISSUE TITLE
No lua files on installation

### ISSUE THREAD

**Issue by Nickiel12** [daurnimator/ldbus#18]
When I try to install this package with
`sudo luarocks install --server=https://luarocks.org/dev ldbus DBUS_INCDIR=/usr/include/dbus-1.0/ DBUS_ARCH_INCDIR=/usr/lib/dbus-1.0/include`

then I run `ls` it just outputs an empty tree:
`ls /usr/local/share/lua/5.3/ldbus/`
`>> message`

**Comment by daurnimator** [comment]
> then I run `ls` it just outputs an empty tree:
> `ls /usr/local/share/lua/5.3/ldbus/`
> `>> message`

That is expected; ldbus is half lua C module half lua module.
Given your path above, it should have also created a file `/usr/local/lib/lua/5.3/ldbus.so`
